name: Sync with foundries repo
on:
  push:
    branches:
    - main
    - development
    - feature/add-workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Set foundries token
      run: |
        echo "TOKEN: ${FOUNDRIES_ACCESS_TOKEN} debug"
        git config --global http.https://source.foundries.io/factories/arduino.extraheader "${FOUNDRIES_ACCESS_TOKEN}"
      env:
        FOUNDRIES_ACCESS_TOKEN: ${{ secrets.FOUNDRIES_ACCESS_TOKEN }}
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: src-repo
      env:
        FOUNDRIES_ACCESS_TOKEN: ${{ secrets.FOUNDRIES_ACCESS_TOKEN }}
        REMOTE_REPO: https://source.foundries.io/factories/arduino/lmp-manifest.git
        BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

